services:
    lab:
        image: jupyter/scipy-notebook:latest
        ports:
           - "8888:8888"
        # network_mode: host 
        environment:
            - JUPYTER_TOKEN=lab
            - NB_UID=1000
            - NB_GID=1000
        volumes:
            - ./test:/home/jovyan/work
        restart: unless-stopped
